{{- $webapp := .Values.georchestra.smtp_smarthost -}}
{{- if $webapp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-smtp
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-smtp
spec:
  replicas: {{ $webapp.replicaCount }}
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-smtp
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-smtp
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-smtp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        {{- with .Values.georchestra.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - name: georchestra-smtp
        image: camptocamp/exim:latest
        env:
          {{- if $webapp.relay_host }}
          - name: RELAY_HOST
            value: {{ $webapp.relay_host }}
          {{- end -}}
          {{- if $webapp.relay_port }}
          - name: RELAY_PORT
            value: {{ $webapp.relay_port | quote }}
          {{- end -}}
          {{- if $webapp.mailname }}
          - name: MAILNAME
            value: {{ $webapp.mailname }}
          {{- end -}}
          {{- if $webapp.postmaster }}
          - name: POSTMASTER
            value: {{ $webapp.postmaster }}
          {{- end -}}
          {{- if $webapp.relay_username }}
          - name: RELAY_USERNAME
            value: {{ $webapp.relay_username }}
          {{- end -}}
          {{- if $webapp.relay_password }}
          - name: RELAY_PASSWORD
            value: {{ $webapp.relay_password }}
          {{ end -}}
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 10 }}
          {{- end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 25
          name: smtp
        livenessProbe:
          tcpSocket:
            port: smtp
          initialDelaySeconds: 30
      {{- if $webapp.tolerations }}
      tolerations:
        {{- $webapp.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- .Values.hostAliases | toYaml | nindent 8 }}
      {{- end }}
{{- end -}}
