{{- $webapp := .Values.georchestra.webapps.geonetwork.kibana -}}
{{- if .Values.georchestra.webapps.geonetwork.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-kibana
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-kibana
spec:
  replicas: {{ $webapp.replicaCount }}
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-kibana
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-gn4-kibana
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-kibana
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        {{- with .Values.georchestra.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - name: kibana
        image: {{ $webapp.image }}
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://{{ include "georchestra.fullname" . }}-gn4-elasticsearch-svc:9200
        ports:
        - containerPort: 5601
          name: kibana
        volumeMounts:
          - mountPath: /usr/share/kibana/config
            name: gn4-kibana-config
      volumes:
      - name: gn4-kibana-config
        configMap:
          name: {{ include "georchestra.fullname" . }}-gn4-kibana-config
      {{- if $webapp.tolerations }}
      tolerations:
        {{- $webapp.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- .Values.hostAliases | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
