{{- $webapp := .Values.georchestra.webapps.mapstore -}}
{{- if $webapp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-mapstore
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-mapstore
spec:
  replicas: {{ $webapp.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-mapstore
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-mapstore
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-mapstore
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        {{- with .Values.georchestra.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      initContainers:
      {{ include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      containers:
      - name: georchestra-mapstore
        image: {{ $webapp.docker_image }}
        imagePullPolicy: Always
        {{ if and $webapp.command $webapp.args -}}
        command:
        {{- range $webapp.command }}
        - {{ . }}
        {{- end }}
        args:
        {{- range $webapp.args }}
        - {{ . }}
        {{- end }}
        {{- end }}
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
          - mountPath: /mnt/mapstore2
            name: mapstore-datadir
        env:
          - name: JAVA_OPTS
            value: -Xms512m -Xmx1G -XX:MaxPermSize=128m -DPRINT_BASE_URL=pdf -Dgeorchestra.datadir=/etc/georchestra -Dgeorchestra.extensions=/mnt/mapstore2
          {{- include "georchestra.ldap-envs" . | nindent 10 }}
          {{- include "georchestra.database-georchestra-envs" . | nindent 10 }}
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 10 }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: http-proxy
        {{- with $webapp.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /mapstore/configs/config.json
            port: 8080
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /mapstore/configs/config.json
            port: 8080
          failureThreshold: 5
          periodSeconds: 15
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      - name: mapstore-datadir
        persistentVolumeClaim:
          claimName: {{ include "georchestra.fullname" . }}-mapstore-datadir
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.registry_secret }}
      imagePullSecrets:
      - name: {{ $webapp.registry_secret }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- .Values.hostAliases | toYaml | nindent 8 }}
      {{- end }}
{{- end }}

